# Generated by Django 4.1.2 on 2022-10-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_client_third_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='return_date',
            field=models.DateField(blank=True, default=None, verbose_name='return date'),
        ),
    ]
