# Generated by Django 4.1.2 on 2022-10-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_credit_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='return_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='return date'),
        ),
    ]
