# Generated by Django 4.1.2 on 2022-10-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_credit_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Third_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
