# Generated by Django 4.1.2 on 2022-10-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_client_third_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Third_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
