# Generated by Django 4.1.2 on 2022-10-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_client_third_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Adress',
            new_name='Address',
        ),
    ]
