# Generated by Django 4.1.1 on 2022-09-30 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frog',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('g', 'green'), ('b', 'blue')], max_length=1)),
                ('age', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(blank=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pepega_in_action.frog')),
            ],
        ),
    ]
